### ISSUE TITLE
[clean] Refactor code to address CodeFactor issues in cleanup branch for PR #37

### ISSUE THREAD

**Issue by chigeekgreg** [kjm015/New-Kyle#42]
**Is your feature request related to a problem? Please describe.**
CodeFactor is currently [complaining](https://www.codefactor.io/repository/github/kjm015/new-kyle/pull/37) about two minor issues in the [cleanup](/kjm015/New-Kyle/tree/cleanup) branch that should be fixed prior to PR #37.

CodeFactor warnings included below for convenience:

---
![Severity: Minor](https://www.codefactor.io/Content/img/issue-severity-Minor.svg "Severity: Minor") **Complex Method** `complexity = 17`
Long or complex methods may lead to code that is difficult to understand and change. Such code may also attract abusive use of comments when a small method or variable are viable alternatives. The key to understand about small methods is good naming. If you have a good name for a method you don't need to look at the body.

**Refactorings**

- [Extract Method](http://sourcemaking.com/refactoring/extract-method)
- [Replace Temp With Query](http://sourcemaking.com/refactoring/replace-temp-with-query)
- [Replace Conditional with Polymorphism](http://sourcemaking.com/refactoring/replace-conditional-with-polymorphism)
- [Replace Method with Method Object](http://sourcemaking.com/refactoring/replace-method-with-method-object)
- [Decompose Conditional](http://sourcemaking.com/refactoring/decompose-conditional)
- [Preserve Whole Object](http://sourcemaking.com/refactoring/preserve-whole-object)
- [Introduce Parameter Object](http://sourcemaking.com/refactoring/introduce-parameter-object)

https://github.com/kjm015/New-Kyle/blob/f7fa67dac3360bfd4fbe0484a7534bd5b60343aa/src/main/kotlin/io/github/kjm015/kylenewer/util/computer/ComputerService.kt#L25-L112

---
![Severity: Major](https://www.codefactor.io/Content/img/issue-severity-Major.svg "Severity: Major") **This comment contains 'TODO:' that has been defined as forbidden in detekt.** `lines of code = 1`
Developers often add comments to code which is not complete or needs review. Most likely you want to fix or review the code, and then remove the comment, before you consider the code to be production ready.

**Further Reading**

- [Detekt - ForbiddenComment](https://detekt.github.io/detekt/style.html#forbiddencomment)

> Have your own [Detekt](https://detekt.github.io/detekt/configurations.html) rules? No problem, simply add **detekt.yml** file to the root of this branch.
> **issue code:** `detekt.ForbiddenComment`

https://github.com/kjm015/New-Kyle/blob/f7fa67dac3360bfd4fbe0484a7534bd5b60343aa/src/main/kotlin/io/github/kjm015/kylenewer/listeners/InfluxListener.kt#L14

---

**Describe the solution you'd like**
* Follow the Source Making recommendations for refactoring the complex method.
* Create an issue to track the planned enhancement and remove the `TODO` comment.

**Describe alternatives you've considered**
* Ignore the complex method for now, since it is a low severity warning.
* Create a `detekt.yml` file to allow `TODO`s in javadoc.

**Additional context**
Some IDEs can track `TODO`s that appear inside javadoc as tasks. However, these tasks might be better tracked in a project management tool, such as GitHub issues, where they can be prioritized appropriately.

**Comment by kjm015** [comment]
Fixed by https://github.com/kjm015/New-Kyle/pull/46
