### ISSUE TITLE
[feature] Implement a message template service for outgoing messages

### ISSUE THREAD

**Issue by chigeekgreg** [kjm015/New-Kyle#43]
Per issue #42, creating an issue to track the `TODO` that appears on line 14 below:
https://github.com/kjm015/New-Kyle/blob/f7fa67dac3360bfd4fbe0484a7534bd5b60343aa/src/main/kotlin/io/github/kjm015/kylenewer/listeners/InfluxListener.kt#L9-L19

**Comment by kjm015** [comment]
This isn't really an issue, it's more of a feature request.
