### ISSUE TITLE
[bug] computer command budget logic is buggy

### ISSUE THREAD

**Issue by chigeekgreg** [kjm015/New-Kyle#45]
**Describe the bug**
* The bot does not make full use of the budget, even when it is capable of generating a more expensive build within the budget constraints. For example, if given a budget of 850, it will spit out a build costing 826.91, but given a budget of 827, it does not provide that build.
* Some budgets cause the bot to throw a NullPointerException, which is always interpreted as a budget that is too low, even when the budget is higher than many valid builds.

**To Reproduce**
1. Ask for a computer with budget of various values between 800-875.
   > !kyle computer 850
2. Notice that the whole budget is not used.
   > Total Cost   | $826.91 
3. Ask for a computer with budget of 900 or 1000. 
   > !kyle computer 900
4. Notice that the bot acts as if the budget is too low.
   > Sorry, it seems you can't afford that right about now!

**Expected behavior**
The bot should always return the best computer available at a given budget, including budget of 900 and 1000.

**Screenshots**
![kyle-computer-bug](https://user-images.githubusercontent.com/91397173/165210004-f260ee39-a0e5-4c60-8415-8d96663e9e14.png)

**Additional context**
Terminal output:
```
2022-04-26 02:39:09.695 ERROR 536 --- [inWS-ReadThread] i.g.k.newkyle.commands.ComputerCommand   : Failed to create PC for user "chigeek" -> java.lang.NullPointerException
```

**Comment by kjm015** [comment]
Fixed by https://github.com/kjm015/New-Kyle/pull/46
